[project]
name = "ai-dial-memory-mcp"
version = "0.1.0"
description = ""
authors = [
    {name = "Aleksei Korota",email = "Aleksei_Korota@epam.com"}
]
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "injector",
    "fastapi-injector",
    "lancedb",
    "pydantic-settings",
    "aidial-client>=0.7.1,<0.8.0",
    "python-json-logger",
    "mcp[cli]",
    "pandas",
]


[tool.poetry.group.dev.dependencies]
ruff = "*"
mypy = "*"
pytest = "*"
pytest-asyncio = "*"
httpx = "*"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.ruff]
target-version = "py313"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.mypy]
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_configs = true
